project_name: vik8s
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386
      - ppc64
      - ppc64le
      - s390x
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'

#dockers:
#  - image_templates: ["ghcr.io/goreleaser/example:{{ .Version }}"]
#    dockerfile: Dockerfile
#    build_flag_templates:
#      - --label=org.opencontainers.image.title={{ .ProjectName }}
#      - --label=org.opencontainers.image.description={{ .ProjectName }}
#      - --label=org.opencontainers.image.url=https://github.com/goreleaser/example
#      - --label=org.opencontainers.image.source=https://github.com/goreleaser/example
#      - --label=org.opencontainers.image.version={{ .Version }}
#      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#      - --label=org.opencontainers.image.revision={{ .FullCommit }}
#      - --label=org.opencontainers.image.licenses=MIT


#nfpms:
#  - maintainer: haiker <ni@renzhen.la>
#    description: very easy install kubernetes cluster
#    homepage: https://github.com/ihaiker/vik8s
#    license: MIT
#    formats:
#      - deb
#      - rpm
#      - apk
