- hosts: all
  become: yes
  gather_facts: true

  tasks:
    - name: centos
      block:
        - name: make root ssh directory
          file:
            path: "${HOME}/.ssh"
            state: directory
        - name: copy authorized_keys
          copy:
            remote_src: true
            src: "/home/vagrant/.ssh/authorized_keys"
            dest: "/root/.ssh/authorized_keys"
            mode: 0600
      when: ansible_distribution == "CentOS"
    - name: yum install jq/vim/net-tools
      yum:
        name: "{{packages}}"
        state: present
      vars:
        packages:
          - jq
          - vim
          - net-tools
          - tree
