apiVersion: v1
kind: Service
metadata:
  name: {{.Kubeadm.ApiServer}}
  namespace: kube-system
spec:
  clusterIP: {{.Kubeadm.ApiServerVIP}}
  selector:
    component: kube-apiserver
  ports:
    - protocol: TCP
      port: 6443
      targetPort: 6443